### ISSUE TITLE
Subscribe from video pages

### ISSUE THREAD

**Issue by Keith94** [shgysk8zer0/youtube-subscribe-addon#4]
Is there any workaround to allow subscribing to channels directly from the upload pages?

**Comment by shgysk8zer0** [comment]
This is a "nice-to-have" feature that I would really like to implement, but it would be difficult to impossible to do in a way that is anything better than fragile. If and when a method is found, it would likely break as soon as YouTube's markup changes.

I'm adding the "help wanted" label in hope that someone gets to this before I do. Here's how I see it working:

1. Add a content script (*currently works only by checking `tab.url`*)
2. Check if this is a video page `url.pathname === 'watch' && url.searchParams.has('v')`
3. Search for channel / user link `link = document.querySelector('#owner-container a, ytd-video-owner-renderer a')`
4. Pass any found link(s) to a URL parser to discover feeds
5. Add a popup for when a video belongs to a user & a channel

Step 3 is the tricky part. YouTube uses shadow DOM and custom elements with non-standard attributes pretty extensively, which makes their HTML difficult to comprehend. They used to use `itemprop`, which would have made this much easier. The example query that I listed can find at least 3 different links on a page (*since a video may belong to both a user & a channel*).

Too bad they don't use their old markup. `document.querySelector('[itemtype="http://schema.org/VideoObject"] [itemprop="creator"] [itemprop="url"]')` would have done the trick, and wold have been more reliable.
